In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

lst = ['red', 'red', 'yellow', 'green', 'yellow']

data = pd.DataFrame(lst,columns = ['color'])
display(data)

color
0     red
1     red
2  yellow
3   green
4  yellow

In [2]:
encoder = OneHotEncoder(sparse = False) #Tạo object encoder
onehot = encoder.fit_transform(data)
print(onehot)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [3]:
print(pd.get_dummies(data)) #Dùng hàm get_dummies() của pandas


   color_green  color_red  color_yellow
0            0          1             0
1            0          1             0
2            0          0             1
3            1          0             0
4            0          0             1


In [4]:
from sklearn.preprocessing import LabelEncoder
encoder1 = LabelEncoder()
label = encoder1.fit_transform(data)
print(label)

[1 1 2 0 2]


C:\Users\congc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   color   5 non-null      object
dtypes: object(1)
memory usage: 168.0+ bytes


In [6]:
data.loc[:,'color'].astype('category').cat.codes

0    1
1    1
2    2
3    0
4    2
dtype: int8

In [11]:
list_2 = ['red', 'green', 'pink', 'yellow', 'orange', 'green', 'red', 'yellow']

data_1 = pd.DataFrame(list_2,columns = ['color'])
onehot_1 = encoder.fit_transform(data_1)
print(onehot_1)

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
label_1 = encoder1.fit_transform(data_1)
print(label_1)

[3 0 2 4 1 0 3 4]


C:\Users\congc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
print(pd.get_dummies(data_1))

   color_green  color_orange  color_pink  color_red  color_yellow
0            0             0           0          1             0
1            1             0           0          0             0
2            0             0           1          0             0
3            0             0           0          0             1
4            0             1           0          0             0
5            1             0           0          0             0
6            0             0           0          1             0
7            0             0           0          0             1


In [14]:
data_1.loc[:,'color'].astype('category').cat.codes

0    3
1    0
2    2
3    4
4    1
5    0
6    3
7    4
dtype: int8

In [15]:
import numpy as np
conditions = [data_1['color'] == 'green',
              data_1['color'] == 'orange',
              data_1['color'] == 'pink',
              data_1['color'] == 'red',
              data_1['color'] == 'yellow']
choices = [1,2,3,4,5]
data_1['Encoder'] = np.select(conditions,choices,default = 'NaN')
print(data_1)

    color Encoder
0     red       4
1   green       1
2    pink       3
3  yellow       5
4  orange       2
5   green       1
6     red       4
7  yellow       5


In [16]:
from sklearn.preprocessing import OrdinalEncoder
list3 = ['excellent', 'very_good' 'good', 'normal', 'bad']
dat3 = pd.DataFrame(list3, columns = ['rate'])
encoder3 = OrdinalEncoder()
oe = encoder3.fit_transform(dat3)
print(oe)

# list_.reverse()
encoder3.categories = [np.array(list3)]
oe2 = encoder3.fit_transform(dat3)
print(oe2)


[[1.]
 [3.]
 [2.]
 [0.]]
[[0.]
 [1.]
 [2.]
 [3.]]


In [19]:
df = pd.read_csv('FoodPrice_in_Turkey.csv')
onehot_2 = encoder.fit_transform(df.loc[:,['ProductName']])
print(onehot_2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
display(pd.get_dummies(df.loc[:,['ProductName']]))

ProductName_Apples (red) - Retail  ProductName_Apples - Retail  \
0                                     0                            0   
1                                     0                            0   
2                                     0                            0   
3                                     0                            0   
4                                     0                            0   
...                                 ...                          ...   
7376                                  0                            0   
7377                                  0                            0   
7378                                  0                            0   
7379                                  0                            0   
7380                                  0                            0   

      ProductName_Bananas - Retail  ProductName_Beans (white) - Retail  \
0                                0                                   0   
1                                0                                   0   
2                                0                                   0   
3                                0                                   0   
4                                0                                   0   
...                            ...                                 ...   
7376                             0                                   0   
7377                             0                                   0   
7378                             0                                   0   
7379                             0                                   0   
7380                             0                                   0   

      ProductName_Bread (common) - Retail  ProductName_Bread (pita) - Retail  \
0                                       0                                  0   
1                                       0                                  0   
2                                       0                                  0   
3                                       0                                  0   
4                                       0                                  0   
...                                   ...                                ...   
7376                                    0                                  0   
7377                                    0                                  0   
7378                                    0                                  0   
7379                                    0                                  0   
7380                                    0                                  0   

      ProductName_Bulgur - Retail  ProductName_Cabbage - Retail  \
0                               0                             0   
1                               0                             0   
2                               0                             0   
3                               0                             0   
4                               0                             0   
...                           ...                           ...   
7376                            0                             0   
7377                            0                             0   
7378                            0                             0   
7379                            0                             0   
7380                            0                             0   

      ProductName_Cauliflower - Retail  ProductName_Cheese - Retail  ...  \
0                                    0                            0  ...   
1                                    0                            0  ...   
2                                    0                            0  ...   
3                                    0                            0  ...   
4                                    0                            0  ...   
...                           